### ISSUE TITLE
Pom with adaptations for tests

### ISSUE THREAD

**Issue by RF-Buerky** [nicolaiparlog/energy-model#20]
It would be nice to get the adapted pom to be able to test with jUnit. Maybe somebody was motivated to copy the new lines Nicolai showed us during our computer science lecture. I on the contrary wanted to try starting an issue by myself.

Of course Nicolai could directly push his branch 'unit-tests-session'. This would be the most appreciated course.

**Comment by EdenTewelde** [comment]
Hier ist meine pom mit den Änderungen. (Allerdings hat bei mir noch kein Test funktioniert -.-)

<?xml version="1.0" encoding="UTF-8"?>
<project
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
		xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<modelVersion>4.0.0</modelVersion>

	<groupId>org.codefx.demo.bingen</groupId>
	<artifactId>energy-model</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<kotlin.version>1.1.2</kotlin.version>
		<main.class>org.codefx.demo.bingen.energy_model.MainKt</main.class>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib</artifactId>
			<version>${kotlin.version}</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
		<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
		<plugins>
			<plugin>
				<artifactId>kotlin-maven-plugin</artifactId>
				<groupId>org.jetbrains.kotlin</groupId>
				<version>${kotlin.version}</version>
				<executions>
					<execution>
						<id>compile</id>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
					<execution>
						<id>test-compile</id>
						<goals>
							<goal>test-compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<archive>
								<manifest>
									<mainClass>${main.class}</mainClass>
								</manifest>
							</archive>
							<descriptorRefs>
								<descriptorRef>jar-with-dependencies</descriptorRef>
							</descriptorRefs>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by nicolaiparlog** [comment]
Argh, I forgot to push my changes. The `master` branch now contains the correct POM and you can start running tests immediately. FYI, the relevant change was this one: 8387a1d.

**Comment by RF-Buerky** [comment]
ok thanks. you can close this issue if you want to. i'm not allowed to do this.

**Comment by nicolaiparlog** [comment]
Fixed by 8387a1d.
