### ISSUE TITLE
improve Account so that all tests in AccountTest pass

### ISSUE THREAD

**Issue by RF-Buerky** [nicolaiparlog/energy-model#21]
# Information
We now have a new Kotlin file called `Account` in our project "energy-model". The path to `Account` is: `energy-model/src/main/kotlin/org/codefx/demo/bingen/energy_model/Account.kt`. You can view the file by clicking [here](https://github.com/nicolaiparlog/energy-model/blob/master/src/main/kotlin/org/codefx/demo/bingen/energy_model/Account.kt).

It was done by puprose that the tests during the build fo the project with Maven don't pass. There are some mistakes in the Kotlin file `Account`.

# Task
Improve the Kotlin file `Account` so that all tests in the test file `AccountTest` pass.

**Comment by nicolaiparlog** [comment]
Thanks for opening the issue. I added some backtick (`) to make code (like class names and file paths) stand out and become more readable.

**Comment by nicolaiparlog** [comment]
Fixed in #29.
