### ISSUE TITLE
implement RomanNumerals so that all tests in RomanNumeralsTest pass

### ISSUE THREAD

**Issue by RF-Buerky** [nicolaiparlog/energy-model#23]
# Information
We now have a new Kotlin file called "RomanNumerals.kt" in our project "energy-model". The path to "RomanNumerals.kt" is:  energy-model/src/main/kotlin/org/codefx/demo/bingen/energy_model/math/RomanNumerals.kt 
You can view the file by clicking [here]( https://github.com/nicolaiparlog/energy-model/blob/master/src/main/kotlin/org/codefx/demo/bingen/energy_model/math/RomanNumerals.kt).

There is no real code in the file. Code have to be added (see tasks). 

There is a test file called "RomanNumeralsTest.kt" in which tests for "RomanNumerals.kt" are prepared. The path to "RomanNumeralsTest.kt" is:  energy-model/src/test/kotlin/org/codefx/demo/bingen/energy_model/math/RomanNumeralsTest.kt 
You can view the file by clicking [here](https://github.com/nicolaiparlog/energy-model/blob/master/src/test/kotlin/org/codefx/demo/bingen/energy_model/math/RomanNumeralsTest.kt)

# Task
Implement RomanNumerals so that all tests in RomanNumeralsTest pass. It suffices to go up to 50.

# Help
FOR BACKGROUND ON ROMAN NUMERALS AND HOW TO CONVERT TO THEM:
     * http://turner.faculty.swau.edu/mathematics/materialslibrary/roman/

**Comment by nicolaiparlog** [comment]
Fixed in #29.
