### ISSUE TITLE
another simple mathematical problem with code and tests

### ISSUE THREAD

**Issue by RF-Buerky** [nicolaiparlog/energy-model#26]
Just as Nicolai demans in his OLAT notes:

"look for another simple mathematical problem like Fibonacci Numbers or Roman Numerals, write about half a dozen tests for it, and try to implement a solution" ([here](https://olat.vcrp.de/auth/RepositoryEntry/1676804160/CourseNode/95828252477131))

Some ideas by somebody?

**Comment by nicolaiparlog** [comment]
* testing whether three numbers are a [Pythagorean triple](https://en.wikipedia.org/wiki/Pythagorean_triple)
* [integer factorization](https://en.wikipedia.org/wiki/Integer_factorization)
* testing whether a number is a [triangular number](https://en.wikipedia.org/wiki/Triangular_number)

**Comment by nicolaiparlog** [comment]
Fixed in #30 and #31.
